# VDM Corner Testbed — baseline vs VDM-regularized (draft v0.1)
# Geometry
H: 1.0              # inlet height (non-dimensional units)
L_in: 3.0           # inlet straight length (multiples of H)
L_out: 5.0          # outlet straight length (multiples of H)
rc: 0.00            # inner fillet radius; set to 0.0 to recover a sharp corner

# Fluid
rho: 1.0            # density
nu: 1e-3            # kinematic viscosity (ν)

# Inlet profile
U0: 1.0             # characteristic inlet speed (can swap to parabolic in notebook)

# Numerics (placeholder; pick your solver later)
Nx: 256             # grid points x-direction
Ny: 256             # grid points y-direction
dt: 1e-3            # time step
t_end: 2.0          # simulation end time

# Baseline boundary conditions
walls: no-slip      # no-penetration + no-slip
inlet: dirichlet    # fixed ux=U0, uy=0
outlet: neumann     # zero-grad (pressure/velocity, depending on solver)

# VDM regularizer (Void Debt Modulation) — toy model parameters
regularizer:
  enabled: true
  beta: 0.6         # coupling of 'debt' to advective transport limiter (1/(1 + beta*D))
  tau_r: 0.5        # debt relaxation time (D decays like -D/tau_r)
  kappa: 1e-3       # diffusion of D (smooth spread)
  alpha: 1.0        # source strength from strain rate |∇u|^2
  tau_u: 0.1        # velocity smoothing timescale used by monitors
  tau_g: 0.5        # global valence accumulation window for triggers

# Outputs
save_streamlines: true
save_vorticity: true
save_maxspeed_scan: true
